# config/config.yaml
server:
  port: "8080"

database:
  host: "localhost"
  port: 5432
  user: "public_config_service"
  password: "public_config_service"
  dbname: "public_config"
  sslmode: "disable"

model:
  baseDir: "./db"
  typesPath: "data/types.json"
  validationsPath: "data/validations.json"
  postgresTypeMapsPath: "postgres/data/type_maps.json"
  attributesPath: "data/attributes.json"
