package datahelpers

const (
	OperatorEquals    = "="
	OperatorNotEquals = "<>"
	// OperatorLessThan          = "<"
	OperatorLessThanEquals = "<="
	// OperatorGreaterThan       = ">"
	OperatorGreaterThanEquals = ">="
	OperatorIn                = "IN"
	OperatorBetween           = "BETWEEN"
	OperatorLike              = "LIKE"
)

const (
	LogicalAnd = "AND"
	LogicalOr  = "OR"
	LogicalNot = "NOT"
)

// Constants for operators and SQL keywords
const (
	// Logical operators
	LogicalAND = "AND"
	LogicalOR  = "OR"
	LogicalNOT = "NOT"

	// Comparison operators
	OperatorEqual              = "="
	OperatorNotEqual           = "!="
	OperatorGreaterThan        = ">"
	OperatorLessThan           = "<"
	OperatorGreaterThanOrEqual = ">="
	OperatorLessThanOrEqual    = "<="
	OperatorIN                 = "IN"
	OperatorNOTIN              = "NOT IN"
	OperatorLIKE               = "LIKE"
	OperatorNOTLIKE            = "NOT LIKE"
	OperatorBETWEEN            = "BETWEEN"
	OperatorNOTBETWEEN         = "NOT BETWEEN"
	OperatorIS                 = "IS"
	OperatorISNOT              = "IS NOT"
	OperatorEXISTS             = "EXISTS"
	OperatorNOTEXISTS          = "NOT EXISTS"

	// SQL keywords
	KeywordSELECT      = "SELECT"
	KeywordFROM        = "FROM"
	KeywordWHERE       = "WHERE"
	KeywordUPDATE      = "UPDATE"
	KeywordSET         = "SET"
	KeywordINSERT      = "INSERT"
	KeywordINTO        = "INTO"
	KeywordVALUES      = "VALUES"
	KeywordDELETE      = "DELETE"
	KeywordDEFAULT     = "DEFAULT"
	KeywordCREATE      = "CREATE"
	KeywordTABLE       = "TABLE"
	KeywordALTER       = "ALTER"
	KeywordADD         = "ADD"
	KeywordDROP        = "DROP"
	KeywordCOLUMN      = "COLUMN"
	KeywordINDEX       = "INDEX"
	KeywordCONSTRAINT  = "CONSTRAINT"
	KeywordPRIMARYKEY  = "PRIMARY KEY"
	KeywordFOREIGNKEY  = "FOREIGN KEY"
	KeywordUNIQUE      = "UNIQUE"
	KeywordCHECK       = "CHECK"
	KeywordREFERENCES  = "REFERENCES"
	KeywordJOIN        = "JOIN"
	KeywordINNERJOIN   = "INNER JOIN"
	KeywordLEFTJOIN    = "LEFT JOIN"
	KeywordRIGHTJOIN   = "RIGHT JOIN"
	KeywordFULLJOIN    = "FULL JOIN"
	KeywordON          = "ON"
	KeywordAS          = "AS"
	KeywordORDERBY     = "ORDER BY"
	KeywordGROUPBY     = "GROUP BY"
	KeywordHAVING      = "HAVING"
	KeywordLIMIT       = "LIMIT"
	KeywordOFFSET      = "OFFSET"
	KeywordUNION       = "UNION"
	KeywordUNIONALL    = "UNION ALL"
	KeywordINTERSECT   = "INTERSECT"
	KeywordEXCEPT      = "EXCEPT"
	KeywordWITH        = "WITH"
	KeywordDISTINCT    = "DISTINCT"
	KeywordCASE        = "CASE"
	KeywordWHEN        = "WHEN"
	KeywordTHEN        = "THEN"
	KeywordELSE        = "ELSE"
	KeywordEND         = "END"
	KeywordNULL        = "NULL"
	KeywordTRUE        = "TRUE"
	KeywordFALSE       = "FALSE"
	KeywordASC         = "ASC"
	KeywordDESC        = "DESC"
	KeywordCASCADE     = "CASCADE"
	KeywordRESTRICT    = "RESTRICT"
	KeywordTRUNCATE    = "TRUNCATE"
	KeywordBEGIN       = "BEGIN"
	KeywordCOMMIT      = "COMMIT"
	KeywordROLLBACK    = "ROLLBACK"
	KeywordTRANSACTION = "TRANSACTION"
	KeywordDO          = "DO"
	KeywordCONFLICT    = "CONFLICT"
	KeywordRETURNING   = "RETURNING"
)
